### ISSUE TITLE
Whitelist Campus-Flutter Web App for CORS

### ISSUE THREAD

**Issue by jakobkoerber** [TUM-Dev/Campus-Backend#252]
Because of the current CORS protection we currently have to use a proxy server to ensure proper testing of the beta web app. Because this is not a good practice it would be great if the Backend could whitelist [web.tum.app](https://web.tum.app/) to ensure proper loading of endpoints and images. Thank you!

**Comment by CommanderStorm** [comment]
I have not tested that this works, but given what had to be configured, I don't see where it would not => closed this issue

**Comment by jakobkoerber** [comment]
<img width="539" alt="image" src="https://github.com/TUM-Dev/Campus-Backend/assets/56073945/8b0c59c4-949c-410e-9d41-4711c8b5c6ee">

Thank you for helping @CommanderStorm! Unfortunately I still experience CORS error in 0.3.0 :/ or is that something I need to fix on the client side?

**Comment by CommanderStorm** [comment]
I have removed all cors-protection by whitelisting any domain to do cors-request (see https://github.com/TUM-Dev/Campus-Backend/commit/c2cf61443b7003a616db9d50d3755d9242092a95).

Found this site and testing seems promising ^^
![image](https://github.com/TUM-Dev/Campus-Backend/assets/26258709/53d1b1f6-91ad-4adb-ad95-6123637fd794)

**Comment by jakobkoerber** [comment]
Thanks again! I hope this is not a security issue :D

I still experience CORS errors for the images of the news entries. But I am not sure if we can influence that

<img width="896" alt="Screenshot 2023-10-14 at 14 14 16" src="https://github.com/TUM-Dev/Campus-Backend/assets/56073945/39a8c392-b4b4-45a6-9518-e7086fab6d94">

**Comment by joschahenningsen** [comment]
We should actually already scrape the images and host them ourselves. I wonder if we have an issue with that currently 🤔

**Comment by joschahenningsen** [comment]
https://github.com/TUM-Dev/Campus-Backend/blob/c2cf61443b7003a616db9d50d3755d9242092a95/server/backend/cron/news.go#L121C18-L121C18 We're downloading the file but save the link to the source image in the database it seems

**Comment by CommanderStorm** [comment]
Actually, we are already serving images: https://github.com/TUM-Dev/Campus-Backend/pull/256
Have I missed changing an API?

**Comment by jakobkoerber** [comment]
This works in theory but the news recently have [https://api.tum.app/files/news/sources/src_1.png](url) set as `imageUrl`, which is always the TUM logo. That's why I use `link` as a fallback, which provides the link to the source image

**Comment by CommanderStorm** [comment]
cannot reproduce for news
![image](https://github.com/TUM-Dev/Campus-Backend/assets/26258709/c86b9be6-b993-4818-9e2a-2c027dea452c)

Have looked at the sources:
Yes, two of the sources had the TUM logo even though they are only vaguely connected to tum
=> adding these two icons:
![image](https://github.com/TUM-Dev/Campus-Backend/assets/26258709/0d21990e-1b76-48bc-a875-45cf8d0b23b9)

**Comment by jakobkoerber** [comment]
> cannot reproduce for news

@CommanderStorm Please take a look at a request like [https://api.tum.app/v1/news/-1?oldestDateAt=2023-09-12T20%3A17%3A46.384Z](url), every news entry has [https://api.tum.app/files/news/sources/src_1.png](url) for `imageUrl` despite having an image provided via `link`. This seems to be a recent bug. I check for that and fallback to `link` since displaying the TUM logo doesn't make sense. This introduces the CORS errors on the web app

**Comment by CommanderStorm** [comment]
I have fixed the entries pointing to this.
Please use the ...Url fields for getting the image and don't use the link property for images.
Link is only where clicking on said news entry should redirect.

**Comment by jakobkoerber** [comment]
Thank you @CommanderStorm! I used `link` as a fallback :D CORS works now properly, I currently get a 404 for a lot of the most recent news, seems to be the case especially since mid of September. Any idea why?

**Comment by CommanderStorm** [comment]
For some news providers (f.ex. newsspread), if we did not catch the images in time, they are gone.
The image URL should only be filled if it is download properly.
Am going to finish up another pr and get to this afterwards
