### ISSUE TITLE
Some tu-film movies don't have an imdb link

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/Campus-Backend#267]
See https://www.tu-film.de/programm/view/1233

=> this breaks the movies cronjob

**Comment by joschahenningsen** [comment]
Who wrote that cronjob?!?

![Ohno.jpg](https://github.com/TUM-Dev/Campus-Backend/assets/44805696/24471480-175f-4f4d-83c3-5a42ec631833)

**Comment by CommanderStorm** [comment]
<img src="https://media4.giphy.com/media/WKX1Ff0QLfBv5H42fX/giphy.gif"/>
