### ISSUE TITLE
New Endpoint "listMeals"

### ISSUE THREAD

**Issue by tobiasjungmann** [TUM-Dev/Campus-Backend#81]
# Why will this be useful
Currently, requests to query meals in a cafeteria in the [eat-api](https://github.com/TUM-Dev/eat-api) returns a lot of additional information. Since this backend has much more capability of altering the data and meals are already stored, this can be added here.

# How can it look like
Instead of returning all additional information, only the meal names should be returned. It should be possible to query them with parameters in the web request to select the cafeteria and the date.

**Comment by elli-hae** [comment]
I'm working on this, since I'm quite new to this it might take a while though :)

**Comment by joschahenningsen** [comment]
I agree it would be nice to have some features here that are not in scope for the eat-api. But we should be a little careful not to 
- replicate functionality that already exists 
- build functionality that can be achieved client side by using the eat-api without huge downsides

@tobiasjungmann what is the intended use case of this endpoint? Is it likely to be used?

**Comment by tobiasjungmann** [comment]
The intended functionality was to be able to load just the meal names from the backend since they are stored there anyways and are needed to create a meal rating (similar workflow to listCanteens). Otherwise both, the backend and the eat-api are necessary for the rating workflow. I did not want to add any additional information, everything else can be loaded from the eat-api. I think this is a dangling issue since the simple endpoint is already implemented. However, if someone has any additional information which can be added we can alter the endpoint.
